# Generated by Django 2.2.16 on 2022-05-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220502_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to='review',
        ),
        migrations.AlterOrderWithRespectTo(
            name='review',
            order_with_respect_to='title',
        ),
    ]
